### PR TITLE
it compiles with errors

### PR DESCRIPTION
**Pull request by benoist**
As mentioned here https://github.com/manastech/crystal/issues/1710

Please note it's got failing specs, but maybe you could help me to make it work again

### CODE REVIEW

**Comment by bararchy** [comment]
@benoist Could you explain what error are you getting ? 
Maybe I can help

**Comment by benoist** [comment]
Spec run against the latest crystal build I get these errors

``` code
Failures:

  1) OpenSSL::Cipher encrypts/decrypts
     Failure/Error: s1.should eq(ciphertext)

       expected: [118, 232, 36, 50, 245, 69, 112, 97, 158, 176, 115, 47, 144, 254, 201, 232, 213, 234, 204, 27, 125, 247, 48, 210, 28, 129, 91, 124, 105, 194, 112, 5]
            got: []

     # ./spec/cipher_spec.cr:29

  2) OpenSSL::PKey::DSA should be able to load DSA from pem

       Neither PUB or PRIV key: error:0D06B08E:asn1 encoding routines:ASN1_D2I_READ_BIO:not enough data
       [4514489842] *CallStack::unwind:Array(Pointer(Void)) +82
       [4514489745] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
       [4514489704] *CallStack::new:CallStack +40
       [4514585089] *Exception@Exception#initialize<OpenSSL::PKey::DSA::DSAError, String?>:CallStack +33
       [4514585382] *OpenSSL::PKey::DSA::DSAError@OpenSSL::OpenSSLError#initialize<OpenSSL::PKey::DSA::DSAError, String>:CallStack +102
       [4514585244] *OpenSSL::PKey::DSA::DSAError::new<String>:OpenSSL::PKey::DSA::DSAError +108
       [4514697132] *OpenSSL::PKey::DSA::new<MemoryIO, Nil>:OpenSSL::PKey::DSA +236
       [4514696885] *OpenSSL::PKey::DSA::new<MemoryIO>:OpenSSL::PKey::DSA +21
       [4514457240] ~fun_literal_45 +56
       [4514452919] *it<String, String, Int32, &( -> Void)>:(Nil | Bool | Array(Spec::Result)) +359
       [4514456121] ~fun_literal_41 +201
       [4514607635] *Spec::RootContext::describe<String, String, Int32, &( -> Void)>:Spec::Context+ +195
       [4514455907] *describe<OpenSSL::PKey::DSA:Class, String, Int32, &( -> Void)>:Spec::Context+ +51
       [4514439427] __crystal_main +25203
       [4514449408] main +32

  3) OpenSSL::PKey::RSA should be able to load RSA from pem

       Invalid EVP_PKEY: error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error
       [4514489842] *CallStack::unwind:Array(Pointer(Void)) +82
       [4514489745] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
       [4514489704] *CallStack::new:CallStack +40
       [4514699329] *Exception@Exception#initialize<OpenSSL::PKey::PKeyError, String?>:CallStack +33
       [4514699190] *OpenSSL::PKey::PKeyError@OpenSSL::OpenSSLError#initialize<OpenSSL::PKey::PKeyError, String>:CallStack +102
       [4514699052] *OpenSSL::PKey::PKeyError::new<String>:OpenSSL::PKey::PKeyError +108
       [4514710318] *OpenSSL::PKey::RSA@OpenSSL::PKey#initialize<OpenSSL::PKey::RSA, Pointer(Void), Bool>:Nil +46
       [4514712610] *OpenSSL::PKey::RSA::new<Pointer(Void), Bool>:OpenSSL::PKey::RSA +98
       [4514712496] *OpenSSL::PKey::RSA::new<MemoryIO, Nil>:OpenSSL::PKey::RSA +96
       [4514712389] *OpenSSL::PKey::RSA::new<MemoryIO>:OpenSSL::PKey::RSA +21
       [4514461672] ~fun_literal_58 +56
       [4514452919] *it<String, String, Int32, &( -> Void)>:(Nil | Bool | Array(Spec::Result)) +359
       [4514459713] ~fun_literal_52 +337
       [4514607635] *Spec::RootContext::describe<String, String, Int32, &( -> Void)>:Spec::Context+ +195
       [4514459363] *describe<OpenSSL::PKey::RSA:Class, String, Int32, &( -> Void)>:Spec::Context+ +51
       [4514439559] __crystal_main +25335
       [4514449408] main +32

Finished in 659.41 milliseconds
17 examples, 1 failures, 2 errors, 0 pending

Failed examples:

crystal spec ./spec/cipher_spec.cr:5 # OpenSSL::Cipher encrypts/decrypts
crystal spec ./spec/dsa_spec.cr:19 # OpenSSL::PKey::DSA should be able to load DSA from pem
crystal spec ./spec/rsa_spec.cr:36 # OpenSSL::PKey::RSA should be able to load RSA from pem
```

**Comment by bararchy** [comment]
@benoist I did some changes and was able to take it this far

1) Changes: 

```
diff --git a/src/cipher/cipher.cr b/src/cipher/cipher.cr
index 359a881..4a93d03 100644
--- a/src/cipher/cipher.cr
+++ b/src/cipher/cipher.cr
@@ -68,7 +68,7 @@ class OpenSSL::Cipher
     if keybytes == 0
       raise Error.new "EVP_BytesToKey"
     end
-    key.length = keybytes
+    key.size = keybytes

     cipherinit key: key, iv: iv

@@ -88,14 +88,14 @@ class OpenSSL::Cipher
       in
     end

-    outl = ina.length + block_size
+    outl = ina.size + block_size
     if outa
       outa.length = outl
     else
       outa = Array(UInt8).new(outl)
     end

-    if LibCrypto.evp_cipherupdate(@ctx, outa, out outl, ina, ina.length) != 1
+    if LibCrypto.evp_cipherupdate(@ctx, outa, pointerof(outl), ina, ina.size) != 1
       raise Error.new "EVP_CipherUpdate"
     end

@@ -107,7 +107,7 @@ class OpenSSL::Cipher
     outl = block_size
     outa = Array(UInt8).new(outl)

-    if LibCrypto.evp_cipherfinal_ex(@ctx, outa, out outl) != 1
+    if LibCrypto.evp_cipherfinal_ex(@ctx, outa, pointerof(outl)) != 1
       raise Error.new "EVP_CipherFinal_ex"
     end

diff --git a/src/digest/digest.cr b/src/digest/digest.cr
index ddda0b6..90cb14f 100644
--- a/src/digest/digest.cr
+++ b/src/digest/digest.cr
@@ -70,7 +70,7 @@ module OpenSSL
     end

     def update(data: String | Slice)
-      LibCrypto.evp_digestupdate(self, data, LibC::SizeT.cast(data.length))
+      LibCrypto.evp_digestupdate(self, data, data.size)
       self
     end

diff --git a/src/digest/digest_base.cr b/src/digest/digest_base.cr
index 428bd1e..bc09ff6 100644
--- a/src/digest/digest_base.cr
+++ b/src/digest/digest_base.cr
@@ -25,7 +25,7 @@ module OpenSSL
     end

     def base64digest
-      Base64.encode64(digest)
+      Base64.encode(digest)
     end

     def hexdigest

```

2) Error:

```
Error in ./spec/dsa_spec.cr:4: instantiating 'describe(OpenSSL::PKey::DSA:Class)'

describe OpenSSL::PKey::DSA do
^~~~~~~~

in /usr/lib/crystal/spec/dsl.cr:3: instantiating 'Spec::RootContext:Class#describe(String, String, Int32)'

    Spec::RootContext.describe(description.to_s, file, line) do |context|
                      ^~~~~~~~

in /usr/lib/crystal/spec/dsl.cr:3: instantiating 'Spec::RootContext:Class#describe(String, String, Int32)'

    Spec::RootContext.describe(description.to_s, file, line) do |context|
                      ^~~~~~~~

in ./spec/dsa_spec.cr:4: instantiating 'describe(OpenSSL::PKey::DSA:Class)'

describe OpenSSL::PKey::DSA do
^~~~~~~~

in ./spec/dsa_spec.cr:5: instantiating 'it(String)'

  it "should be able to generate DSA key" do
  ^~

in ./spec/dsa_spec.cr:5: instantiating 'it(String)'

  it "should be able to generate DSA key" do
  ^~

in ./spec/dsa_spec.cr:9: instantiating 'OpenSSL::PKey::DSA#to_pem()'

    dsa.to_pem.match(/PRIVATE KEY/).should_not be_nil
        ^~~~~~

in ./src/pkey/pkey.cr:63: instantiating 'to_pem(StringIO)'

      to_pem(io)
      ^~~~~~

in ./src/pkey/dsa.cr:60: instantiating 'IO:Module#copy(OpenSSL::MemBIO, StringIO)'

      IO.copy(bio, io)
         ^~~~

in /usr/lib/crystal/io.cr:769: no overload matches 'OpenSSL::MemBIO#read' with types Slice(UInt8)
Overloads are:
 - OpenSSL::MemBIO#read(data : Slice(UInt8), count)
 - OpenSSL::MemBIO#read(slice : Slice(UInt8))
 - OpenSSL::MemBIO#read(count : Int)
 - OpenSSL::MemBIO#read()

    while (len = src.read(buffer.to_slice).to_i32) > 0
                     ^~~~


```

**Comment by benoist** [comment]
Did you use my feature branch or did you use master?

**Comment by bararchy** [comment]
@benoist Used yours, with the 0.8.0+ branch

**Comment by bararchy** [comment]
@benoist Also, I use `Crystal 0.8.0 [e363b63] (Sat Sep 19 19:10:07 UTC 2015)`

**Comment by benoist** [comment]
I'm on the crystal IRC. That might be easier :)

**Comment by bararchy** [comment]
@benoist latest Crystal now, getting this issue: 

```
Error in ./spec/cipher_spec.cr:24: instantiating 'OpenSSL::Cipher#update(String)'

    s1 = c1.update("DATA")
            ^~~~~~

instantiating 'update(String, Nil)'

in ./src/cipher/cipher.cr:102: undefined method 'length=' for Array(UInt8)

    outa.length = outl
         ^~~~~~

================================================================================

Array(UInt8) trace:

  ./src/cipher/cipher.cr:95

          outa = Array(UInt8).new(outl)
          ^~~~

  ./src/cipher/cipher.cr:95

          outa = Array(UInt8).new(outl)
                              ^~~

```

**Comment by bararchy** [comment]
@datanoise Could you please take a look and see if you can help us "stable" it so it could be pulled into the STDlib ?

**Comment by benoist** [comment]
@bararchy @datanoise ok latest commit makes all specs green

**Comment by bararchy** [comment]
@benoist I think we should just fork Crystal, make the changes to OpenSSL in the STDlib and PR upstream.
I don't think there is a point to PR this repo, I dont even know when datanoise is going to pull it if even.

**Comment by benoist** [comment]
Yes I was thinking about doing that. But we'll have to split it up in separate PR and do it step by step. This will make sure we review every implementations and use the correct alternatives like replacing arrays with slices.
@datanoise is that ok with you?

**Comment by bararchy** [comment]
@benoist he said it's ok, here --> https://github.com/manastech/crystal/issues/1710#issuecomment-146387408

**Comment by benoist** [comment]
Thats good enough for me :-)

**Comment by bararchy** [comment]
@benoist If I can help with something ping me (Mail, comment or IRC)

**Comment by datanoise** [comment]
I've committed the changes to make it run on crystal 0.9

**Pull request closed without merging**
